### ISSUE TITLE
Increasing the concurrency during load testing will result in a panic

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#359]
Executing the following command will result in an error.

* command
```console
go run cmd/runn/main.go loadt --concurrent 2  testdata/book/include_main.yml
```
* result
```log
.. snip ..
fatal error: concurrent map writes

goroutine 3757 [running]:
github.com/k1LoW/runn.(*store).recordAsMapped(...)
        /workspaces/runn/store.go:31
github.com/k1LoW/runn.(*operator).recordAsMapped(...)
        /workspaces/runn/operator.go:128
github.com/k1LoW/runn.(*operator).record(0xc0003f16c0, 0xc09b6dfd10?)
        /workspaces/runn/operator.go:108 +0x13e
github.com/k1LoW/runn.(*includeRunner).Run(0xc000014760, {0x1487eb8, 0xc09b755280}, 0xc0003918c0)
        /workspaces/runn/include.go:74 +0xa5f
github.com/k1LoW/runn.(*operator).runInternal.func2.1(0xc09b75e540?)
        /workspaces/runn/operator.go:784 +0xfee
github.com/k1LoW/runn.(*operator).runInternal.func2(0xc08f6cd938, 0xc0003f16c0, 0xc08f6cd908, {0x1487eb8, 0xc09b755280})
        /workspaces/runn/operator.go:898 +0x52d
github.com/k1LoW/runn.(*operator).runInternal(0xc0003f16c0, {0x1487eb8, 0xc09b755280})
        /workspaces/runn/operator.go:903 +0x5e5
github.com/k1LoW/runn.(*operator).run(0xc0003f16c0, {0x1487eb8?, 0xc09b755280})
        /workspaces/runn/operator.go:541 +0x189
github.com/k1LoW/runn.(*operators).RunN.func1()
        /workspaces/runn/operator.go:1089 +0x14f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

.. snip ..
```

or 

```log
.. snip ..
panic: runtime error: index out of range [1] with length 1

goroutine 50 [running]:
github.com/k1LoW/runn.(*operator).recordAsMapped(...)
        /Users/runner/work/runn/runn/operator.go:127
github.com/k1LoW/runn.(*operator).record(0x14090533a40, 0x1409173f200?)
        /Users/runner/work/runn/runn/operator.go:108 +0x338
github.com/k1LoW/runn.(*httpRunner).Run(0x140000a6f60, {0x1038bee18, 0x14000daae40}, 0x14091181650)
        /Users/runner/work/runn/runn/http.go:313 +0x938
github.com/k1LoW/runn.(*operator).runInternal.func2.1(0x14090cda180?)
        /Users/runner/work/runn/runn/operator.go:718 +0xe0
github.com/k1LoW/runn.(*operator).runInternal.func2(0x140907dab48, 0x14090533a40, 0x140907dab18, {0x1038bee18, 0x14000daae40})
        /Users/runner/work/runn/runn/operator.go:898 +0x3c0
github.com/k1LoW/runn.(*operator).runInternal(0x14090533a40, {0x1038bee18, 0x14000daae40})
.. snip ..
```

**Comment by k1LoW** [comment]
Thank you for your report!

**Comment by k2tzumi** [comment]
@k1LoW 
Thank you for your quick response. The problem has been resolved!
