### ISSUE TITLE
Regression: flattenYamlAliases() breaks CRLF encoded runbooks in a certain situation

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#751]
Hi. I noticed that the `flattenYamlAliases()` breaks backward compatibility in a certain situation.

### Reproduction

1. Save the following contents as `spanner_1.yml` with **CRLF** (IMPORTANT) line endings
    ```yaml
    desc: Test using Spanner with CRLF line endings
    runners:
      db: spanner://test-project/test-instance/test-database
    vars:
      query: 'SELECT 1;'
    steps:
      - db:
          # NOTE: the ':' character is important here
          query: |
            {{ true ? vars.query : vars.query }}
    ```
2. Launch Spanner emulator
    ```bash
    docker run -p 9010:9010 -p 9020:9020 gcr.io/cloud-spanner-emulator/emulator
    ```
3. Setup the database
    ```bash
    docker run -eSPANNER_EMULATOR_HOST=localhost:9010 --network=host google/cloud-sdk:slim bash -c 'gcloud config configurations create emulator && gcloud config set auth/disable_credentials true && gcloud config set project test-project && gcloud config set api_endpoint_overrides/spanner http://localhost:9020/ && gcloud spanner instances create test-instance --config=emulator-config --description="Test Instance" --nodes=1 && gcloud spanner databases create test-database --instance=test-instance'
    ```
4. runn run
    ```bash
    # the following command fails only runn v0.93.0 or later
    SPANNER_EMULATOR_HOST=localhost:9010 runn run spanner_1.yml
    ```
5. 
    <details>
    <summary>:boom: panic occurs inside of the go-sql-spanner library</summary>

    ```bash
    ❯ SPANNER_EMULATOR_HOST=localhost:9010 runn run spanner_1.yml
    .
    
    panic: runtime error: slice bounds out of range [:6] with length 0
    
    goroutine 11 [running]:
    github.com/googleapis/go-sql-spanner.isDDL({0xc00090b1a8?, 0xc00090b1a8?})
	    /Users/*****/go/1.21.5/pkg/mod/github.com/googleapis/go-sql-spanner@v1.1.1/statement_parser.go:313 +0xf8
    github.com/googleapis/go-sql-spanner.(*conn).ExecContext(0xc00090d720, {0x2c60730, 0xc0000cd180}, {0xc00090b1a8, 0x1}, {0x3e08f60, 0x0, 0x0})
	    /Users/*****/go/1.21.5/pkg/mod/github.com/googleapis/go-sql-spanner@v1.1.1/driver.go:855 +0xb3
    database/sql.ctxDriverExec({0x2c60730?, 0xc0000cd180?}, {0x4b5b6d60?, 0xc00090d720?}, {0x0?, 0x0?}, {0xc00090b1a8?, 0x2636880?}, {0x3e08f60, 0x0, ...})
	    /Users/*****/.goenv/versions/1.21.5/src/database/sql/ctxutil.go:31 +0xd7
    database/sql.(*DB).execDC.func2()
	    /Users/*****/.goenv/versions/1.21.5/src/database/sql/sql.go:1675 +0x165
    database/sql.withLock({0x2c59118, 0xc0010ee090}, 0xc000aeedb0)
	    /Users/*****/.goenv/versions/1.21.5/src/database/sql/sql.go:3502 +0x82
    database/sql.(*DB).execDC(0xc000a86630?, {0x2c60730?, 0xc0000cd180}, 0xc0010ee090, 0xc000aeeea0?, {0xc00090b1a8, 0x1}, {0x0, 0x0, 0x0})
	    /Users/*****/.goenv/versions/1.21.5/src/database/sql/sql.go:1670 +0x24f
    database/sql.(*Tx).ExecContext(0xc000a96300, {0x2c60730, 0xc0000cd180}, {0xc00090b1a8, 0x1}, {0x0, 0x0, 0x0})
	    /Users/*****/.goenv/versions/1.21.5/src/database/sql/sql.go:2478 +0xad
    github.com/golang-sql/sqlexp/nest.(*Tx).ExecContext(...)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/golang-sql/sqlexp@v0.1.0/nest/nest.go:124
    github.com/k1LoW/runn.(*dbRunner).run.func1(0xc000aef230, 0xc000a80730, {0x2c60730, 0xc0000cd180}, 0xc000aef1f8, 0xc000210c00, 0xc000bb6900)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/db.go:130 +0x24a
    github.com/k1LoW/runn.(*dbRunner).run(0xc000bb6900, {0x2c60730, 0xc0000cd180}, 0xc000012948, 0xc000c3f680)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/db.go:241 +0x2e5
    github.com/k1LoW/runn.(*dbRunner).Run(0x255cfe0?, {0x2c60730, 0xc0000cd180}, 0xc000c3f680)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/db.go:92 +0x106
    github.com/k1LoW/runn.(*operator).runStep.func1(0xc000908700?)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/operator.go:178 +0x1d0
    github.com/k1LoW/runn.(*operator).runStep(0xc000210c00, {0x2c60730?, 0xc0000cd180}, 0x0, 0xc000c3f680)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/operator.go:313 +0x7af
    github.com/k1LoW/runn.(*operator).runInternal(0xc000210c00, {0x2c60730, 0xc0000cd180})
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/operator.go:1020 +0x69b
    github.com/k1LoW/runn.(*operator).run(0xc000210c00, {0x2c60730?, 0xc0000cd180})
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/operator.go:845 +0x225
    github.com/k1LoW/runn.(*operators).runN.func1()
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/operator.go:1437 +0x233
    github.com/k1LoW/concgroup.(*Group).Go.func1()
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/concgroup@v1.0.0/concgroup.go:37 +0x86
    golang.org/x/sync/errgroup.(*Group).Go.func1()
	    /Users/*****/go/1.21.5/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75 +0x56
    created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	    /Users/*****/go/1.21.5/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:72 +0x96
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x23bbfb6]
    
    goroutine 1 [running]:
    github.com/k1LoW/runn.simplifyStepResults({0xc00091e490, 0x1, 0xc000574300?})
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/result.go:282 +0x76
    github.com/k1LoW/runn.simplifyRunResult(0xc000ac2630)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/result.go:272 +0x119
    github.com/k1LoW/runn.(*runNResult).simplify(0x2c3c680?)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/result.go:171 +0xd7
    github.com/k1LoW/runn.(*runNResult).Out(0xc000ac1bf0, {0x2c3c680, 0xc000132030}, 0x1)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/result.go:114 +0xfe
    github.com/k1LoW/runn/cmd.glob..func6(0xc00015a400?, {0xc00090e120?, 0x4?, 0x2973cdd?})
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/cmd/run.go:74 +0x1d5
    github.com/spf13/cobra.(*Command).execute(0x3dc4500, {0xc00090e0f0, 0x1, 0x1})
	    /Users/*****/go/1.21.5/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x87c
    github.com/spf13/cobra.(*Command).ExecuteC(0x3dc3f40)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
    github.com/spf13/cobra.(*Command).Execute(...)
	    /Users/*****/go/1.21.5/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
    github.com/k1LoW/runn/cmd.Execute()
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/cmd/root.go:44 +0x1a
    main.main()
	    /Users/*****/go/1.21.5/pkg/mod/github.com/k1!lo!w/runn@v0.93.0/cmd/runn/main.go:32 +0xf
    ```
    </details>

---

### Suggested solution

Replacing all CRLFs with LFs before passing the file contents to go-yaml in `flattenYamlAliases()`.

```diff
--- a/runbook.go
+++ b/runbook.go
@@ -136,7 +136,10 @@ func flattenYamlAliases(in []byte) ([]byte, error) {

        var tmp any

-       err := goyaml.UnmarshalWithOptions(in, &tmp, decOpts...)
+       // CRLF causes issue with go-sql-spanner
+       in_lf := ([]byte)(strings.ReplaceAll(string(in), "\r\n", "\n"))
+
+       err := goyaml.UnmarshalWithOptions(in_lf, &tmp, decOpts...)
        if err != nil {
                return nil, err
        }
```

**Comment by k1LoW** [comment]
@h6ah4i Thank you for your report!

It was an error caused by CRs in queries and has been corrected.
